user:
  dir: d:\code_generator_output

spring:
  datasource:
    url: jdbc:mysql://localhost:3316/space_time?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

server:
  port: 8080